'use client';

import { useState, useEffect } from 'react';
import {
  Sparkles,
  X,
  Bot,
  ArrowRight,
  Check,
  Layers,
  FileText,
  DollarSign,
  Wand2,
  ListPlus,
  RotateCcw,
} from 'lucide-react';
import type { QuoteLineItem } from '@saas/shared';
import { calculateQuoteTotals } from '@saas/shared';
import { Button } from '@/components/ui/button';
import { formatCurrency } from './quote-lines-table';
import { toast } from 'sonner';

export interface GeneratedQuoteDraft {
  title?: string;
  items: QuoteLineItem[];
  paymentTerms?: string;
  termsAndConditions?: string;
  notes?: string;
  currency?: string;
  prompt: string;
}

interface QuoteAiDrawerProps {
  open: boolean;
  onClose: () => void;
  onApply: (draft: GeneratedQuoteDraft) => void;
  currentCurrency?: string;
}

const TEMPLATES = [
  {
    title: 'Enterprise CRM Implementation',
    description: '3 phases: Platform setup, data migration, and annual SLA support.',
    prompt:
      'Quote for Enterprise CRM Rollout:\nPhase 1: Cloud Architecture & Setup - 1 package at $6,500.\nPhase 2: Custom Temporal Workflows & Migration - 80 hours at $150/hr with 10% volume discount.\nPhase 3: 24/7 SLA Support Retainer - 12 months at $1,200/mo with 5% VAT.\nPayment Terms: Net 30 days.',
  },
  {
    title: 'Cloud Security Audit & Compliance',
    description: 'Full infrastructure pen-test and ISO/SOC2 compliance audit.',
    prompt:
      'Comprehensive Cloud Security Engagement:\nSection 1: Infrastructure Assessment\n- Multi-Cloud IAM & Kubernetes Security Audit: 1 Package @ $5,500\n- External Penetration Testing: 40 Hours @ $175/hr (5% discount)\nSection 2: Remediation & Compliance\n- Automated Vulnerability Pipeline: 1 Package @ $4,000\nNote: Includes executive summary presentation and ISO27001 readiness matrix.\nPayment terms: Net 15 days.',
  },
  {
    title: 'AI Agent & LLM Automation',
    description: 'Custom AI orchestration and fine-tuned model workflows.',
    prompt:
      'AI CRM Automation System:\nPhase 1: Agentic Workflow Design & Prompt Engineering: 60 Hours @ $160/hr with 10% partner discount.\nPhase 2: Temporal State Machine Integration: 1 System @ $8,000.\nNote: High availability SLA with 99.9% uptime guarantee.\nMonthly LLM Maintenance Retainer: 6 Months @ $2,000/mo (Tax exempt).\nPayment terms: Net 30.',
  },
];

/**
 * Intelligent parser simulating AI extraction of quotation sections, products, notes,
 * and financial metadata from free-form natural language or RFP text.
 */
function parsePromptToQuote(promptText: string, defaultCurrency = 'USD'): GeneratedQuoteDraft {
  const lines = promptText.split('\n').map((l) => l.trim()).filter(Boolean);
  const items: QuoteLineItem[] = [];

  let currentSection = '';
  let title = 'AI Generated Quotation';
  let paymentTerms = 'net_30';
  let termsAndConditions = 'All work performed under standard Master Services Agreement. Net 30 payment terms apply.';
  let notes = `Draft generated by AI Copilot from prompt: "${promptText.substring(0, 100)}..."`;

  // Try to detect title from first line
  if (lines.length > 0 && !lines[0].toLowerCase().includes('section') && !lines[0].toLowerCase().includes('phase')) {
    const firstLineClean = lines[0].replace(/^(quote for|proposal for|rfp:?)\s*/i, '').trim();
    if (firstLineClean.length > 3 && firstLineClean.length < 80) {
      title = firstLineClean;
    }
  }

  // Detect payment terms in text
  const lowerText = promptText.toLowerCase();
  if (lowerText.includes('immediate') || lowerText.includes('due on receipt')) {
    paymentTerms = 'immediate';
  } else if (lowerText.includes('net 15') || lowerText.includes('net15') || lowerText.includes('15 days')) {
    paymentTerms = 'net_15';
  } else if (lowerText.includes('net 60') || lowerText.includes('net60') || lowerText.includes('60 days')) {
    paymentTerms = 'net_60';
  } else if (lowerText.includes('end of month') || lowerText.includes('eom')) {
    paymentTerms = 'end_of_month';
  } else {
    paymentTerms = 'net_30';
  }

  let lineCounter = 1;

  for (const line of lines) {
    const trimmed = line.trim();

    // Check if section header
    if (/^(phase|section|module|part|deliverable)\s*\d*[:\-]/i.test(trimmed) || /^[A-Z\s]{4,30}:$/.test(trimmed)) {
      currentSection = trimmed.replace(/^[-*•]\s*/, '');
      items.push({
        id: `ai_sec_${lineCounter++}`,
        type: 'section',
        description: currentSection,
      });
      continue;
    }

    // Check if note
    if (/^(note|sla|terms|condition|disclaimer)[:\-]/i.test(trimmed)) {
      items.push({
        id: `ai_note_${lineCounter++}`,
        type: 'note',
        description: trimmed.replace(/^[-*•]\s*/, ''),
      });
      continue;
    }

    // Attempt product parsing
    // Example patterns:
    // "Cloud Architecture & Setup - 1 package at $6,500"
    // "Custom Temporal Workflows & Migration - 80 hours at $150/hr with 10% discount"
    // "- External Penetration Testing: 40 Hours @ $175/hr (5% discount)"
    const cleanLine = trimmed.replace(/^[-*•]\s*/, '');

    // Extract price ($X,XXX or @ $XXX)
    const priceMatch = cleanLine.match(/\$\s?([\d,]+(?:\.\d{2})?)/);
    const unitPrice = priceMatch ? parseFloat(priceMatch[1].replace(/,/g, '')) : 1000;

    // Extract quantity and UoM
    let quantity = 1;
    let uom = 'Units';

    const qtyMatch = cleanLine.match(/(\d+)\s*(hours|hrs|days|months|mo|licenses|units|packages|systems|packages)/i);
    if (qtyMatch) {
      quantity = parseInt(qtyMatch[1], 10);
      const rawUom = qtyMatch[2].toLowerCase();
      if (rawUom.startsWith('hour') || rawUom === 'hrs') uom = 'Hours';
      else if (rawUom.startsWith('day')) uom = 'Days';
      else if (rawUom.startsWith('month') || rawUom === 'mo') uom = 'Months';
      else if (rawUom.startsWith('license')) uom = 'Licenses';
      else if (rawUom.startsWith('package')) uom = 'Packages';
      else uom = 'Units';
    }

    // Extract discount percentage
    let discount = 0;
    const discMatch = cleanLine.match(/(\d+)%\s*(?:discount|off)/i);
    if (discMatch) {
      discount = parseInt(discMatch[1], 10);
    }

    // Extract Tax rate
    let taxRate = 0;
    const taxMatch = cleanLine.match(/(\d+)%\s*(?:vat|tax)/i);
    if (taxMatch) {
      taxRate = parseInt(taxMatch[1], 10);
    }

    // Clean description by stripping numbers/price hints
    let description = cleanLine
      .replace(/\$\s?[\d,]+(?:\.\d{2})?/g, '')
      .replace(/@\s*[\d,]+/g, '')
      .replace(/\b(at|@|with|for)\b.*$/i, '')
      .replace(/^[:\-–\s]+|[:\-–\s]+$/g, '')
      .trim();

    if (!description) {
      description = `Service Item ${lineCounter}`;
    }

    const gross = quantity * unitPrice;
    const discountVal = gross * (discount / 100);
    const subtotal = Number((gross - discountVal).toFixed(2));

    items.push({
      id: `ai_item_${lineCounter++}`,
      type: 'product',
      description,
      quantity,
      uom,
      unitPrice,
      discount,
      taxRate,
      subtotal,
    });
  }

  // If no items were parsed, provide a robust default set
  if (items.filter((i) => i.type === 'product').length === 0) {
    items.push(
      {
        id: `ai_sec_1`,
        type: 'section',
        description: 'Phase 1: Professional Engineering & Delivery',
      },
      {
        id: `ai_item_1`,
        type: 'product',
        description: promptText.slice(0, 50) || 'Custom AI Solution Architecture',
        quantity: 1,
        uom: 'Packages',
        unitPrice: 5000,
        discount: 0,
        taxRate: 0,
        subtotal: 5000,
      },
      {
        id: `ai_note_1`,
        type: 'note',
        description: 'Includes implementation, testing, and 30 days post-launch support warranty.',
      },
    );
  }

  return {
    title,
    items,
    paymentTerms,
    termsAndConditions,
    notes,
    currency: defaultCurrency,
    prompt: promptText,
  };
}

export function QuoteAiDrawer({
  open,
  onClose,
  onApply,
  currentCurrency = 'USD',
}: QuoteAiDrawerProps) {
  const [prompt, setPrompt] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [generatedDraft, setGeneratedDraft] = useState<GeneratedQuoteDraft | null>(null);

  // Close on Escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && open) onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [open, onClose]);

  const handleGenerate = () => {
    if (!prompt.trim()) {
      toast.error('Please enter a prompt or choose a template.');
      return;
    }

    setIsAnalyzing(true);
    setGeneratedDraft(null);

    // Simulate AI synthesis with natural micro-delay
    setTimeout(() => {
      const draft = parsePromptToQuote(prompt.trim(), currentCurrency);
      setGeneratedDraft(draft);
      setIsAnalyzing(false);
      toast.success('AI quotation structure generated successfully!');
    }, 600);
  };

  const handleApply = () => {
    if (!generatedDraft) return;
    onApply(generatedDraft);
    toast.success('Generated lines & settings applied to quotation!');
    onClose();
  };

  const handleUseTemplate = (templatePrompt: string) => {
    setPrompt(templatePrompt);
  };

  if (!open) return null;

  const totals = generatedDraft ? calculateQuoteTotals(generatedDraft.items) : null;

  return (
    <div className="fixed inset-0 z-50 overflow-hidden" role="dialog" aria-modal="true">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/50 backdrop-blur-xs transition-opacity animate-in fade-in duration-200"
        onClick={onClose}
      />

      <div className="fixed inset-y-0 right-0 flex max-w-full pl-10">
        <div className="w-screen max-w-2xl transform bg-surface shadow-2xl transition-all duration-300 ease-in-out border-l border-border flex flex-col">
          {/* Drawer Header */}
          <div className="flex items-center justify-between border-b border-border px-6 py-4.5 bg-gradient-to-r from-brand-soft/60 via-surface to-surface">
            <div className="flex items-center gap-3">
              <span className="grid size-10 place-items-center rounded-xl bg-brand text-white shadow-sm">
                <Sparkles className="size-5" />
              </span>
              <div>
                <h2 className="text-base font-bold tracking-tight text-ink flex items-center gap-2">
                  <span>AI Quotation Copilot</span>
                  <span className="rounded-full bg-brand-soft px-2 py-0.5 text-[11px] font-semibold text-brand">
                    v2.0
                  </span>
                </h2>
                <p className="text-xs text-ink-muted">
                  Transform requirements, RFPs, and scopes into structured Odoo quotes.
                </p>
              </div>
            </div>

            <button
              type="button"
              onClick={onClose}
              className="rounded-lg p-2 text-ink-subtle hover:bg-surface-muted hover:text-ink transition-colors"
              aria-label="Close drawer"
            >
              <X className="size-5" />
            </button>
          </div>

          {/* Drawer Body */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6 scrollbar-thin">
            {/* Quick Templates */}
            <div className="space-y-2">
              <label className="text-xs font-semibold text-ink-muted uppercase tracking-wider flex items-center gap-1.5">
                <Wand2 className="size-3.5 text-brand" />
                <span>Quick Prompt Presets</span>
              </label>
              <div className="grid gap-2 sm:grid-cols-3">
                {TEMPLATES.map((tmpl) => (
                  <button
                    key={tmpl.title}
                    type="button"
                    onClick={() => handleUseTemplate(tmpl.prompt)}
                    className="flex flex-col text-left p-2.5 rounded-lg border border-border bg-surface-muted/30 hover:border-brand hover:bg-brand-soft/30 transition-all text-xs group"
                  >
                    <span className="font-semibold text-ink group-hover:text-brand">
                      {tmpl.title}
                    </span>
                    <span className="text-[11px] text-ink-subtle mt-0.5 line-clamp-2">
                      {tmpl.description}
                    </span>
                  </button>
                ))}
              </div>
            </div>

            {/* Prompt Textarea */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-ink-muted uppercase tracking-wider">
                  Describe Quote Requirements or Paste RFP
                </label>
                {prompt && (
                  <button
                    type="button"
                    onClick={() => setPrompt('')}
                    className="text-xs text-ink-subtle hover:text-danger flex items-center gap-1 transition-colors"
                  >
                    <RotateCcw className="size-3" />
                    Clear
                  </button>
                )}
              </div>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Example: Quote for ACME Corp: Phase 1 Cloud Architecture ($5,000), Phase 2 Custom Temporal Workflow 80 hrs @ $150/hr with 10% discount, and 12-month 24/7 SLA ($1,200/mo, 5% VAT). Payment terms Net 30."
                rows={5}
                className="w-full rounded-xl border border-border bg-surface p-3.5 text-sm leading-relaxed text-ink placeholder:text-ink-subtle focus:border-brand focus:ring-1 focus:ring-brand focus:outline-hidden"
              />
            </div>

            {/* Generate Action Button */}
            <Button
              type="button"
              variant="primary"
              loading={isAnalyzing}
              onClick={handleGenerate}
              className="w-full py-2.5 shadow-sm text-sm font-semibold"
            >
              <Sparkles className="size-4 mr-2" />
              {isAnalyzing ? 'Analyzing & Structuring Quotation...' : 'Analyze & Generate Quotation'}
            </Button>

            {/* AI Generated Preview */}
            {generatedDraft && totals && (
              <div className="space-y-4 rounded-xl border border-brand/40 bg-brand-soft/10 p-5 animate-in fade-in duration-300">
                <div className="flex items-center justify-between border-b border-brand/20 pb-3">
                  <div className="flex items-center gap-2">
                    <Bot className="size-4 text-brand" />
                    <span className="text-sm font-bold text-ink">
                      Structured Quotation Preview
                    </span>
                  </div>
                  <span className="rounded-full bg-brand-soft px-2.5 py-0.5 text-xs font-semibold text-brand">
                    {generatedDraft.items.length} items parsed
                  </span>
                </div>

                {/* Title and metadata */}
                <div className="grid grid-cols-2 gap-3 text-xs bg-surface/80 rounded-lg p-3 border border-border/80">
                  <div>
                    <span className="text-ink-subtle block">Suggested Title</span>
                    <span className="font-semibold text-ink">{generatedDraft.title}</span>
                  </div>
                  <div>
                    <span className="text-ink-subtle block">Payment Terms</span>
                    <span className="font-semibold text-ink uppercase">
                      {generatedDraft.paymentTerms}
                    </span>
                  </div>
                </div>

                {/* Parsed Line Items List */}
                <div className="space-y-2">
                  <span className="text-xs font-semibold text-ink-muted uppercase tracking-wider block">
                    Extracted Lines
                  </span>
                  <div className="divide-y divide-border/60 rounded-lg border border-border bg-surface overflow-hidden">
                    {generatedDraft.items.map((item) => {
                      if (item.type === 'section') {
                        return (
                          <div
                            key={item.id}
                            className="flex items-center gap-2 bg-surface-muted/60 px-3 py-2 text-xs font-semibold text-ink"
                          >
                            <Layers className="size-3.5 text-brand shrink-0" />
                            <span>{item.description}</span>
                          </div>
                        );
                      }
                      if (item.type === 'note') {
                        return (
                          <div
                            key={item.id}
                            className="flex items-center gap-2 bg-surface/40 px-3 py-1.5 text-xs italic text-ink-muted"
                          >
                            <FileText className="size-3.5 text-amber-500 shrink-0" />
                            <span>{item.description}</span>
                          </div>
                        );
                      }

                      return (
                        <div
                          key={item.id}
                          className="flex items-center justify-between px-3 py-2 text-xs hover:bg-surface-muted/20"
                        >
                          <div className="min-w-0 flex-1 pr-2">
                            <p className="font-medium text-ink truncate">{item.description}</p>
                            <p className="text-[11px] text-ink-subtle">
                              {item.quantity} {item.uom} × {formatCurrency(item.unitPrice || 0, currentCurrency)}
                              {(item.discount || 0) > 0 && ` (${item.discount}% off)`}
                              {(item.taxRate || 0) > 0 && ` [${item.taxRate}% tax]`}
                            </p>
                          </div>
                          <span className="font-semibold text-ink tabular-nums shrink-0">
                            {formatCurrency(item.subtotal || 0, currentCurrency)}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Financial Summary */}
                <div className="rounded-lg bg-surface p-3.5 border border-border space-y-1.5 text-xs">
                  <div className="flex justify-between text-ink-muted">
                    <span>Untaxed Subtotal:</span>
                    <span className="font-medium text-ink tabular-nums">
                      {formatCurrency(totals.subtotalAmount, currentCurrency)}
                    </span>
                  </div>
                  {totals.discountAmount > 0 && (
                    <div className="flex justify-between text-emerald-600 dark:text-emerald-400">
                      <span>Total Savings / Discount:</span>
                      <span className="font-medium tabular-nums">
                        -{formatCurrency(totals.discountAmount, currentCurrency)}
                      </span>
                    </div>
                  )}
                  <div className="flex justify-between text-ink-muted">
                    <span>Taxes:</span>
                    <span className="font-medium text-ink tabular-nums">
                      {formatCurrency(totals.taxAmount, currentCurrency)}
                    </span>
                  </div>
                  <div className="flex justify-between text-sm font-bold text-ink border-t border-border/80 pt-2 mt-1">
                    <span>Estimated Total:</span>
                    <span className="text-brand tabular-nums">
                      {formatCurrency(totals.totalAmount, currentCurrency)}
                    </span>
                  </div>
                </div>

                {/* 1-Click Apply */}
                <Button
                  type="button"
                  variant="primary"
                  onClick={handleApply}
                  className="w-full py-2.5 font-semibold text-sm shadow-md"
                >
                  <Check className="size-4 mr-2 stroke-[2.5]" />
                  Apply to Quotation Form
                </Button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
